[package]
name = "net-share-enumeration"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.61.1", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_NetworkManagement_NetManagement"
] }
once_cell = "1.17.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"   
chrono = "0.4"
