[package]
name = "gather_creds"
version = "0.1.0"
edition = "2021"
authors = ["M.Rauch"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.4"
chrono = { version = "0.4", features = ["serde"] }
aho-corasick = "1"
